# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from caesarCipherEncrypt import *
from AESEncrypt import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cipherencrypt = QtWidgets.QPushButton(self.centralwidget,clicked= lambda : press())
        self.cipherencrypt.setGeometry(QtCore.QRect(310, 190, 171, 25))
        self.cipherencrypt.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.cipherencrypt.setObjectName("cipherencrypt")
        self.aesencrypt = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:press2())
        self.aesencrypt.setGeometry(QtCore.QRect(310, 240, 171, 25))
        self.aesencrypt.setStyleSheet("background-color  :rgb(173, 127, 168)")
        self.aesencrypt.setObjectName("aesencrypt")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(210, 140, 371, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget,)
        self.label.setGeometry(QtCore.QRect(280, 310, 251, 81))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, -20, 291, 191))
        self.label_2.setObjectName("label_2")
        self.aesencrypt.raise_()
        self.cipherencrypt.raise_()
        self.plainTextEdit.raise_()
        self.label.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        def press() :
            k=self.plainTextEdit.toPlainText()
            d=ci(k)
            self.label.setText('')
            self.label.setText(d)
            self.label.setFont(QtGui.QFont('Helvetica',30))
        def press2() :
            k=self.plainTextEdit.toPlainText()
            d=ae(k)
            self.label.setText('')
            s=str(d)
            self.label.setText(s)
            self.label.setFont(QtGui.QFont('Helvetica',25))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cipherencrypt.setText(_translate("MainWindow", "cipher Encrypt"))
        self.aesencrypt.setText(_translate("MainWindow", "AES encrypt"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/><span style=\" font-size:48pt;\"></span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">Kikou</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
